//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafffe_Sytem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bill_has_Products = new HashSet<Bill_has_Products>();
        }
    
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public int P_Quantity { get; set; }
        public double P_Price { get; set; }
        public string P_Code { get; set; }
        public Nullable<int> P_Cat_Id { get; set; }
        public Nullable<int> P_Of_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_has_Products> Bill_has_Products { get; set; }
        public virtual Category Category { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
